### ISSUE TITLE
Make node pool auth scope an input

### ISSUE THREAD

**Issue by ivanfetch** [FairwindsOps/terraform-gke#5]
Capturing a comment from @dosullivan  from PR #3 

Another thought for future functionality: perhaps we could pull out the oauth scope list as a module parameter. I don't think this will be necessary in a lot of cases (as the default list will suffice), but it could come up in environments with lots of GCP services in use.

**Comment by bbensky** [comment]
This would be helpful because I wasn't able to add it to make external-dns work with Cloud DNS.
